### ISSUE TITLE
Example Build Fails - Can't Find vscode-languageserver/lib/protocol?

### ISSUE THREAD

**Issue by blewis13** [TypeFox/theia-sprotty-example#23]
Mac OS High Sierra 10.13.3
npm 5.6.0
node v8.11.1

Code appears to exist, but when running the theia-electron example with npm run start, I get the following error:

Uncaught Exception:
Error: Cannot find module 'vscode-languageserver/lib/protocol'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename

Within the theia-electron directory, I do see the *.js file for protocol:

ls node_modules/vscode-languageserver/lib/pro*
node_modules/vscode-languageserver/lib/protocol.d.ts	node_modules/vscode-languageserver/lib/protocol.js

Is there a version dependency on npm/node that would cause this to build improperly? I didn't see any errors during npm install nor npm run build.

thea-app example fails in apparently the same way.

> theia-dsl-app@ start:backend /Users/blewis/git/theia-sprotty-example/theia-app
[watch-deps] > node ./lib/backend/main.js --root-dir=../workspace
[watch-deps] 
[watch-deps] module.js:549
[watch-deps]     throw err;
[watch-deps]     ^
[watch-deps] 
[watch-deps] Error: Cannot find module 'vscode-languageserver/lib/protocol'
[watch-deps]     at Function.Module._resolveFilename (module.js:547:15)

Sorry, I'm sure these issues are meant for code base only, but I didn't know who else to advise. Google searches were not any help.

**Comment by JanKoehnlein** [comment]
The theia-sprotty-example is build on old versions of the underlying libs and frameworks and is no longer maintained. Sorry.
Please have a look at the `@theia/yangster` repository for an uptodate integration of theia and sprotty.
